name: otel-ebpf-profiler
title: OpenTelemetry eBPF Profiler
version: '0.133.0'
summary: Whole-system, cross-language profiler for Linux via eBPF.
description: |
  An OpenTelemetry Collector distribution that is made specifically to be used as a whole-system,
  cross-language profiler for Linux via eBPF.
contact: 
  - michael.dmitry@canonical.com
website:
  - https://github.com/canonical/otel-ebpf-profiler-snap
issues: 
  - https://github.com/canonical/otel-ebpf-profiler-snap/issues
icon: ./logo.svg
license: Apache-2.0
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
confinement: classic
apps:
  otel-ebpf-profiler:
    daemon: simple
    # command: /bin/otel-ebpf-profiler --feature-gates service.profilesSupport --config /etc/otel-ebpf-profiler/config.yaml 2>&1  | tee -a "/var/log/otel-ebpf-profiler.log"
    command: command-wrapper 
    install-mode: disable
    restart-condition: on-failure
parts:
  wrapper:
    plugin: dump
    source: ./snap/
    source-type: local
    override-build: |
      install -D local/command-wrapper $CRAFT_PART_INSTALL/
  config:
    plugin: dump
    source: ./snap/
    source-type: local
    override-build: |
      install -D config.yaml $CRAFT_PART_INSTALL/
  ebpf-profiler:
    plugin: dump
    source-type: tar
    source: 
      - to amd64: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.131.0/otelcol-ebpf-profiler_0.133.0_linux_amd64.tar.gz
      - to arm64: https://github.com/open-telemetry/opentelemetry-collector-releases/releases/download/v0.131.0/otelcol-ebpf-profiler_0.133.0_linux_arm64.tar.gz
      - else: fail
    override-build: |
      install -D -m755 otelcol-ebpf-profiler $SNAPCRAFT_PART_INSTALL/bin/otel-ebpf-profiler
