name: otel-ebpf-profiler
title: OpenTelemetry eBPF Profiler
version: '0.133.0'
summary: Whole-system, cross-language profiler for Linux via eBPF.
description: |
  An OpenTelemetry Collector distribution that is made specifically to be used as a whole-system,
  cross-language profiler for Linux via eBPF.
contact: 
  - michael.dmitry@canonical.com
website:
  - https://github.com/canonical/otel-ebpf-profiler-snap
issues: 
  - https://github.com/canonical/otel-ebpf-profiler-snap/issues
icon: ./logo.svg
license: Apache-2.0
base: core24
platforms:
  amd64:
    build-on: [amd64]
    build-for: [amd64]
  arm64:
    build-on: [arm64]
    build-for: [arm64]
confinement: classic
apps:
  otel-ebpf-profiler:
    daemon: simple
    # command: /bin/otel-ebpf-profiler --feature-gates service.profilesSupport --config /etc/otel-ebpf-profiler/config.yaml 2>&1  | tee -a "/var/log/otel-ebpf-profiler.log"
    command: command-wrapper 
    install-mode: disable
    restart-condition: on-failure
parts:
  wrapper:
    plugin: dump
    source: ./snap/
    source-type: local
    override-build: |
      install -D $CRAFT_PART_SRC/local/command-wrapper $CRAFT_PART_INSTALL/
  config:
    plugin: dump
    source: ./snap/
    source-type: local
    override-build: |
      install -D $CRAFT_PART_SRC/config.yaml $CRAFT_PART_INSTALL/
  ocb:
    plugin: go
    source: "https://github.com/open-telemetry/opentelemetry-collector.git"
    source-type: "git"
    source-tag: "v0.133.0"
    source-depth: 1
    build-snaps:
      - go/1.24/stable
    override-build: |
      cd cmd/builder
      CGO_ENABLED=0 go build -trimpath -o ${CRAFT_PART_INSTALL}/bin/builder .
    prime:
      - "-*"
  ebpf-profiler:
    after:
      - ocb
    plugin: dump
    source: .
    build-packages:
      - wget
    override-build: |
      # Create the binary
      wget https://raw.githubusercontent.com/open-telemetry/opentelemetry-collector-releases/refs/tags/v0.133.0/distributions/otelcol-ebpf-profiler/manifest.yaml -O ${CRAFT_PART_BUILD}/manifest.yaml
      # Starting from v0.0.202531, the eBPF profiler build no longer requires CGO.
      # By disabling CGO, we ensure the resulting binary is fully static.
      # This eliminates the linter warnings about missing dynamic linker.
      CGO_ENABLED=0 builder --config="${CRAFT_PART_BUILD}/manifest.yaml"
      install -D -m755 ${CRAFT_PART_BUILD}/_build/otelcol-ebpf-profiler ${CRAFT_PART_INSTALL}/bin/otel-ebpf-profiler

