# Build and release the snap on merge to main

name: Release Snap

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

env:
  SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}

jobs:
  build-and-test:
    name: Quality Checks
    uses: ./.github/workflows/_build-and-test-snap.yaml
    secrets: inherit
  release-snaps:
    needs:
    - build-and-test
    strategy:
      matrix:
        arch: [amd64, arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Download snap artifact
        uses: actions/download-artifact@v4
        with:
          name: snap-${{ matrix.arch }}
          path: .
      - name: Install dependencies
        run: |
          sudo snap install --classic --channel edge snapcraft
      - name: Upload and release snap
        run: snapcraft upload --release edge otel-ebpf-profiler_*_${{ matrix.arch }}.snap
